version: '3'

tasks:
  default:
    desc: Run the default task
    cmds:
      - task test
      - task format
      - task build

  test:
    desc: Run tests for the project
    cmds:
      - go test ./...

  format:
    desc: Format the codebase
    cmds:
      - gofmt -w .
      - goimports -w .
